name: 'Setup AWS Cli Action'
description: 'setup aws-cli'
branding:
  icon: 'cloud'
  color: 'orange'
runs:
  using: "composite"
  steps:
    - name: Install aws cli
      run: | 
        python -m pip install --upgrade pip awscli awscli-plugin-endpoint
      shell: bash
    - run: aws --version
      shell: bash
